### ISSUE TITLE
Access to game data from FMS API

### ISSUE THREAD

**Issue by brettbbonner** [Mechanical-Advantage/RobotCode2018#1]
Investigate and understand the Field Management System API for accessing game data.

Provide interface function(s) enabling easy access to necessary data (switch/scale ownership) based on that data.

**Comment by e-bonner** [comment]
Jaci has a library for this.

**Comment by brettbbonner** [comment]
Incorporated MatchData library.  Nick tested the APIs using Driver Station input of switch/scale ends and the APIs worked as expected.
