### ISSUE TITLE
Fill in drive code for 2018 (third) robot

### ISSUE THREAD

**Issue by brettbbonner** [Mechanical-Advantage/RobotCode2018#2]
Now that the code is structured to support 3 robots, fill in all the places necessary for the 2018 competition robot drive to function.  Assume tank drive, 2 motors per side, 2-speed gearboxes.

**Comment by e-bonner** [comment]
Have support for specifying tuning parameters but still need support for shifting gearbox.

**Comment by e-bonner** [comment]
Shifting gearbox support added.
