### ISSUE TITLE
Investigate avoiding scale while driving.

### ISSUE THREAD

**Issue by e-bonner** [Mechanical-Advantage/RobotCode2018#22]
Running into the scale is a tech foul so we should investigate ways of preventing that. Possible ideas include:

- Pinpoint sensor pointed up to detect plate
- Ultrasonic sensor
- Field position tracking
- Detecting white tape on the carpet

**Comment by brettbbonner** [comment]
Plan is to use Banner reflective sensor pointed at carpet and driver indicator of state.  Shows red when the white tape is detected.

Code is in place for this.
