### ISSUE TITLE
Test behavior of autonomous when robot encounters immovable object

### ISSUE THREAD

**Issue by brettbbonner** [Mechanical-Advantage/RobotCode2018#25]
Make sure that robot autonomous does not get stuck if it hits an immovable object and the wheels won't turn.  May require simulating this condition on Everybot since behavior of Revenge's shifting gearbox varies depending on low/high gear setting.

**Comment by e-bonner** [comment]
Motion profiling works as long as angle is not off because it does not do distance convergence, DriveDistanceOnHeading now can detect when the robot is stuck and stop automatically.
